export interface Fruit {
  id: number;
  name: string;
  emoji: string;
  stars: number;
  price: number;
  shipDate: string;
  categories: string[];
  tags?: string[];
  onSale?: boolean;
  saleDiscount?: number;
}

export const fruits: Fruit[] = [
  {
    id: 1,
    name: "Red Apple",
    emoji: "🍎",
    stars: 3.5,
    price: 2.98,
    shipDate: "2019-01-20",
    categories: ["domestic", "sweet", "red"],
    tags: ["Best Seller"],
  },
  {
    id: 2,
    name: "Green Apple",
    emoji: "🍏",
    stars: 4.0,
    price: 3.01,
    shipDate: "2019-01-18",
    categories: ["domestic", "tangy", "green"],
  },
  {
    id: 3,
    name: "Yellow Banana",
    emoji: "🍌",
    stars: 4.5,
    price: 5.25,
    shipDate: "2019-01-20",
    categories: ["domestic", "sweet", "yellow"],
    tags: ["Fruitazon's Choice"],
  },
  {
    id: 4,
    name: "Red Grapes",
    emoji: "🍇",
    stars: 4.0,
    price: 6.2,
    shipDate: "2019-01-21",
    categories: ["domestic", "sweet", "red"],
    tags: ["Best Seller"],
  },
  {
    id: 5,
    name: "Green Melon",
    emoji: "🍈",
    stars: 3.5,
    price: 4.0,
    shipDate: "2019-01-19",
    categories: ["exotic", "sweet", "green"],
  },
  {
    id: 6,
    name: "Watermelon",
    emoji: "🍉",
    stars: 4.5,
    price: 3.25,
    shipDate: "2019-01-22",
    categories: ["domestic", "sweet"],
    tags: ["Fruitazon's Choice"],
  },
  {
    id: 7,
    name: "Lemon",
    emoji: "🍋",
    stars: 3.0,
    price: 2.25,
    shipDate: "2019-01-20",
    categories: ["domestic", "tangy", "yellow"],
    tags: ["Best Seller"],
  },
  {
    id: 8,
    name: "Orange",
    emoji: "🍊",
    stars: 3.5,
    price: 4.75,
    shipDate: "2019-01-19",
    categories: ["domestic", "tangy", "orange"],
  },
  {
    id: 9,
    name: "Pineapple",
    emoji: "🍍",
    stars: 5.0,
    price: 9.75,
    shipDate: "2019-01-22",
    categories: ["exotic", "tangy"],
    tags: ["Fruitazon's Choice"],
  },
  {
    id: 10,
    name: "Pear",
    emoji: "🍐",
    stars: 4.5,
    price: 4.25,
    onSale: true,
    saleDiscount: 0.1,
    shipDate: "2019-01-21",
    categories: ["domestic", "sweet"],
  },
  {
    id: 11,
    name: "Peach",
    emoji: "🍑",
    stars: 3.0,
    price: 5.0,
    shipDate: "2019-01-19",
    categories: ["domestic", "tangy"],
    onSale: true,
    saleDiscount: 0.1,
  },
  {
    id: 12,
    name: "Cherry",
    emoji: "🍒",
    stars: 3.5,
    price: 7.0,
    shipDate: "2019-01-20",
    categories: ["domestic", "tangy", "red"],
    tags: ["Best Seller"],
    onSale: true,
    saleDiscount: 0.2,
  },
  {
    id: 13,
    name: "Strawberry",
    emoji: "🍓",
    stars: 4.0,
    price: 8.25,
    shipDate: "2019-01-25",
    categories: ["domestic", "tangy", "sweet", "red"],
  },
  {
    id: 14,
    name: "Kiwi",
    emoji: "🥝",
    stars: 4.5,
    price: 9.25,
    shipDate: "2019-01-23",
    categories: ["exotic", "sweet", "green"],
  },
  {
    id: 15,
    name: "Coconut",
    emoji: "🥥",
    stars: 4.0,
    price: 6.5,
    shipDate: "2019-01-20",
    categories: ["exotic", "sweet", "white"],
    onSale: true,
    saleDiscount: 0.1,
  },
];
